# Generated by Django 3.2.1 on 2021-09-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(default='$', max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('ref', models.CharField(blank=True, max_length=200, null=True)),
                ('bal', models.CharField(blank=True, max_length=200, null=True)),
                ('btc', models.CharField(blank=True, max_length=200, null=True)),
                ('eth', models.CharField(blank=True, max_length=200, null=True)),
                ('promo', models.CharField(blank=True, max_length=200, null=True)),
                ('ref_promo', models.CharField(blank=True, max_length=200, null=True)),
                ('bank', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_n', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_num', models.CharField(blank=True, max_length=200, null=True)),
                ('card_n', models.CharField(blank=True, max_length=200, null=True)),
                ('card_num', models.CharField(blank=True, max_length=200, null=True)),
                ('card_date', models.CharField(blank=True, max_length=200, null=True)),
                ('card_ccv', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
