# Generated by Django 3.2.1 on 2021-09-13 09:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exocoinapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='member',
            name='trade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
