# Generated by Django 3.2.1 on 2021-09-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exocoinapp', '0002_auto_20210913_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='prof',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='bal',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='btc',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='eth',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='promo',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='ref_promo',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
