# Generated by Django 3.2.1 on 2021-09-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exocoinapp', '0003_auto_20210913_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, default='starter', max_length=200, null=True),
        ),
    ]
