# Generated by Django 3.2.1 on 2021-09-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exocoinapp', '0004_alter_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='plan',
            field=models.CharField(blank=True, default='starter', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
