# Generated by Django 3.2.1 on 2021-09-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exocoinapp', '0005_auto_20210913_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('site', models.CharField(default='site', max_length=200, primary_key=True, serialize=False)),
                ('btc_wallet', models.CharField(blank=True, max_length=2000, null=True)),
                ('eth_wallet', models.CharField(blank=True, max_length=2000, null=True)),
                ('phone', models.CharField(blank=True, max_length=2000, null=True)),
                ('email', models.CharField(blank=True, max_length=2000, null=True)),
                ('add', models.CharField(blank=True, max_length=2000, null=True)),
                ('admin', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
