# Generated by Django 3.2.1 on 2021-09-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exocoinapp', '0006_manage'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='robot',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
