# Generated by Django 3.2.1 on 2021-09-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exocoinapp', '0007_member_robot'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=2000, null=True)),
                ('amount', models.CharField(blank=True, max_length=2000, null=True)),
                ('date', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=2000, null=True)),
                ('add', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
