# Generated by Django 3.2.1 on 2021-09-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exocoinapp', '0011_auto_20210915_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='status',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='msg',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
