# Generated by Django 3.2.1 on 2022-01-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exocoinapp', '0013_member_payslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
