# Generated by Django 3.2.1 on 2022-06-25 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exocoinapp', '0014_auto_20220107_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 25, 19, 58, 22, 62442), null=True),
        ),
    ]
